#!/usr/bin/env bash
#patching up the nginx to listen on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# delete the /etc/nginx/sites-enabled/default and create a symlink
sudo service nginx start
