#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443, and 80.


# Install ufw if not installed
apt-get update
apt-get install -y ufw

# Enable IPv6 in ufw if it's not already enabled
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Reset and apply ufw rules
ufw --force reset

# set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH, HTTP, and HTTPS traffic
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

# enable ufw forcefully
ufw --force enable

# Display ufw status for verification
ufw status verbose
