#!/usr/bin/env bash

# This script sets up Nginx configuration for the application

server {
    listen 80;
    listen [::]:80;

    location /airbnb-onepage/ {
	proxy_pass      http://127.0.0.1:5000;
    }
}