#!/usr/bin/env bash

# This script sets up Nginx configuration for the application
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
server {
       listen 80;
       listen [::]:80;

       location /airbnb-onepage/ {
              proxy_pass      http://127.0.0.1:5000;
       }
       location ~ ^/airbnb-dynamic/number_odd_or_even/(\d+)$ {
                proxy_pass      http://127.0.0.1:5001/number_odd_or_even/$1;
       }
}