#!/usr/bin/env bash

# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
server {
    listen 80;
    listen [::]:80;

    location /airbnb-onepage/ {
	proxy_pass      http://127.0.0.1:5000;
    }
    location /number_odd_or_even/ {
	proxy_pass      http://127.0.0.1:5001;
    }
    location /api/ {
	proxy_pass      http://127.0.0.1:5002;
    }
}