#!/usr/bin/env bash

# Default server configuration
#

# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
server {
	listen 80;
	listen [::]:80;

	root   /home/ubuntu/AirBnB_clone_v4/web_dynamic;

	location / {
		  proxy_pass      http://127.0.0.1:5003/2-hbnb;
	}

	location /static/ {
	}

	location /api/ {
		 proxy_pass      http://127.0.0.1:5002;
	}
}